Add support for assigning and unassigning tasks
AY2425S1-CS2103T-F15-4/tp pull request #205
Opened 2024-11-02 16:31 UTC by DanzaSeah

To be added in next PR
Create field in task, List of person that the task is assigned to 
Mark/unmark commands

2024-11-04 17:02 UTC, tingxuanp commented
It seems like the current sample data has tasks assigned to people who are not yet vendors, is it possible to assign tasks to vendors only in the sample data?
![image](https://github.com/user-attachments/assets/30cc2200-6d2e-4204-bf6b-f9066b14c804)

2024-11-06 04:09 UTC, DanzaSeah commented
> It seems like the current sample data has tasks assigned to people who are not yet vendors, is it possible to assign tasks to vendors only in the sample data? ![image](https://private-user-images.githubusercontent.com/144128912/382847060-30cc2200-6d2e-4204-bf6b-f9066b14c804.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NjQ4MDAsIm5iZiI6MTczMDg2NDUwMCwicGF0aCI6Ii8xNDQxMjg5MTIvMzgyODQ3MDYwLTMwY2MyMjAwLTZkMmUtNDIwNC1iZjZiLWY5MDY2YjE0YzgwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQwMzQxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDRiMWI1ZWIxNGYxYzM4ZGY2YTIzODczZmY4MGNjMjRkMGNjZjNhNWUzOTdlZWUyOGQ4NjUzYjQ1OWJmZGYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BFYOLJOuddodX096mmd4VyiZsC2TIFYymVz2t_rgzy0)

Sure, i'll make the changes

2024-11-06 14:05 UTC, dasha3412 requested changes
LGTM, concern is adding functionality for when a vendor is unassigned, the task should be unassigned from that former vendor also (currently, task remains assigned I believe)

2024-11-06 14:36 UTC, DanzaSeah commented on src/main/java/seedu/address/logic/commands/task/CreateTaskCommand.java
> +    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Creates one or more tasks in the address book. \n"
> concern is adding functionality for when a vendor is unassigned, the task should be unassigned from that former vendor
That's true, i'll create an issue and implement it in the next pr, thanks

2024-11-07 04:13 UTC, HanB1n reviewed
LGTM

2024-11-07 04:15 UTC, merged